name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup z88dk
        run: |
          sudo snap install --beta z88dk
          sudo snap alias z88dk.zcc zcc
          sudo snap alias z88dk.z88dk-z80asm z88dk-z80asm
          sudo snap alias z88dk.z88dk-ticks z88dk-ticks
          sudo snap alias z88dk.z88dk-dis z88dk-dis
          sudo snap alias z88dk.z88dk-appmake z88dk-appmake
      - name: Setup ptp2wav
        run: |
          sudo apt-get install -y fpc
          wget https://raw.githubusercontent.com/vargaviktor/primotools/master/win32/PTP2WAV.PAS
          fpc PTP2WAV.PAS
          sudo mv PTP2WAV /usr/local/bin/ptp2wav
      - name: Build
        run: make wav
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            raktaros.ptp
            raktaros.wav
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
