name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup z88dk
        run: |
          sudo snap install --edge z88dk
          sudo snap alias z88dk.zcc zcc
          sudo snap alias z88dk.z88dk-z80asm z88dk-z80asm
          sudo snap alias z88dk.z88dk-ticks z88dk-ticks
          sudo snap alias z88dk.z88dk-dis z88dk-dis
          sudo snap alias z88dk.z88dk-appmake z88dk-appmake
      - name: Build PTP
        run: make
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: raktaros.ptp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
